query allEventos($categoryId: String){
    allEventos(where: {category: $categoryId}) {
        edges {
            node {
                title
                description
                featured_image
                category {
                    ... on Event_category {
                        category_name
                        _meta {
                            uid
                        }
                    }
                }
                _meta {
                    id
                    uid
                    firstPublicationDate
                    lastPublicationDate
                }
                body {
                    __typename
                    ... on EventoBodyText {
                        type
                        label
                        primary {
                            text
                        }
                    }
                    ... on EventoBodyImage {
                        type
                        label
                        primary {
                            image
                        }
                    }
                    ... on EventoBodyEmbed {
                        type
                        label
                        primary {
                            embed
                        }
                    }
                }
            }
        }
    }
}