backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

media_library:
  name: uploadcare
  config:
    publicKey: ef4aabe94d3c70720696
    imageShrink: 1600x1600 70%

site_url: https://projetoanjodaguarda.org

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'events'
    label: 'Eventos'
    folder: 'assets/content/events'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Foto', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data do Evento', name: 'date', widget: 'datetime' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Fotos da Galeria'
        name: 'galleryMedias'
        widget: 'list'
        allow_add: true
        collapsed: false
        fields:
          - {
              label: 'Foto',
              name: 'image',
              widget: 'image'
          }
          - {
              label: 'Título (google)',
              name: 'title',
              widget: 'string'
          }
          - {
              label: 'Texto ALT (google)',
              name: 'altText',
              widget: 'string'
          }
          - {
              label: 'Legenda (opcional)',
              name: 'description',
              widget: 'string'
          }


  - name: 'galleries'
    label: 'Galerias'
    folder: 'assets/content/galleries'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Foto', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Data da galeria', name: 'date', widget: 'datetime' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Fotos da Galeria'
        name: 'galleryMedias'
        widget: 'list'
        allow_add: true
        collapsed: false
        fields:
          - {
              label: 'Foto',
              name: 'image',
              widget: 'image'
          }
          - {
              label: 'Título (google)',
              name: 'title',
              widget: 'string'
          }
          - {
              label: 'Texto ALT (google)',
              name: 'altText',
              widget: 'string'
          }
          - {
              label: 'Legenda (opcional)',
              name: 'description',
              widget: 'string'
          }


  - label: "Páginas"
    name: "paginas"
    format: 'json'
    files:
      - label: "Home"
        name: "home"
        file: "assets/content/home.json"
        fields:
          - label: 'Seção Intro'
            name: 'sectionIntro'
            widget: 'object'
            fields:
              - {
                  label: 'Título',
                  name: 'title',
                  widget: 'string'
                }
              - { 
                  label: 'Texto', 
                  name: 'text', 
                  widget: 'string' 
                }
              - {
                  label: 'Texto do botão',
                  name: 'buttonText',
                  widget: 'string',
                }

          - label: 'Seção Cases'
            name: 'sectionCases'
            widget: 'object'
            fields:
              - { label: 'Título', name: 'title', widget: 'string' }
              - { label: 'Texto', name: 'text', widget: 'string' }
              - label: 'Cases'
                name: 'cases' 
                widget: 'list'
                allow_add: true
                collapsed: false
                fields:
                  - {
                      label: 'Foto',
                      name: 'image',
                      widget: 'image'
                  }
                  - {
                      label: 'Título',
                      name: 'title',
                      widget: 'string'
                  }
                  - {
                      label: 'Texto',
                      name: 'text',
                      widget: 'string'
                  }
              - label: 'Texto do botão'
                name: 'buttonText'
                widget: 'string'

          - label: 'Seção Quem Somos'
            name: 'sectionAbout'
            widget: 'object'
            fields:
              - { label: 'Título', name: 'title', widget: 'string' }
              - { label: 'Texto', name: 'body', widget: 'markdown' }
              - label: 'Texto do botão'
                name: 'buttonText'
                widget: 'string'

          - label: 'Seção Final'
            name: 'sectionWaiting'
            widget: 'object'
            fields:
              - { label: 'Título', name: 'title', widget: 'string' }
              - { label: 'Texto', name: 'text', widget: 'string' }
              - label: 'Texto do botão'
                name: 'buttonText'
                widget: 'string'

      - label: "Quem Somos"
        name: "about"
        file: "assets/content/about.json"
        fields:
          - {
              label: 'Foto',
              name: 'image',
              widget: 'image'
            }
          - {
              label: 'Título',
              name: 'title',
              widget: 'string'
            }
          - { 
              label: 'Texto', 
              name: 'body', 
              widget: 'markdown' 
            }
          - {
              label: 'Texto do botão 1',
              name: 'button1Text',
              widget: 'string',
            }
          - {
              label: 'Texto do botão 2',
              name: 'button2Text',
              widget: 'string',
            }
          - {
              label: 'Texto do botão CTA',
              name: 'buttonCtaText',
              widget: 'string',
            }


